.\" man page for zfetch
.TH zfetch 1 "March 2024" "github.com/Arturmes/zfetch" "Fetch Script"

.SH NAME
.P
zfetch - simple but pretty fetch script

.SH SYNOPSIS
.P
zfetch
.P
arg="[nologo | nofetch]" zfetch

.SH DESCRIPTION
.P
zfetch is a utility that gathers and shows information about your system.

.SH OPTIONS
.P
See the SYNOPSIS for an example of this.
